[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "keboola-mcp-server"
version = "0.1.0"
description = "MCP server for interacting with Keboola Connection"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "mcp[cli]",
    "kbcstorage",
    "httpx",
    "pandas"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "black",
    "isort",
    "mypy",
    "pandas-stubs"
]

[project.scripts]
keboola-mcp = "keboola_mcp_server.cli:main"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3

[tool.hatch.build.targets.wheel]
packages = ["src/keboola_mcp_server"]

[tool.pytest.ini_options]
addopts = "--cov=keboola_mcp_server --cov-report=term-missing --cov-report=xml"
testpaths = ["tests"]
asyncio_mode = "strict"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
show_error_codes = true
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
