name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Build, test and package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests with coverage
        run: |
          pytest --junitxml ./test-results.xml

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if a previous step failed
        with:
          name: Test results (${{ matrix.python-version }})
          path: ./test-results.xml
          reporter: 'java-junit'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Check formatting with black
        run: black . --check

      - name: Build wheels package
        run: |
          python -m build --wheel

      - name: Get package version
        id: get_version
        run: |
          VERSION=`python3 -c 'import importlib.metadata; print(importlib.metadata.version("keboola_mcp_server"))'`
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Upload wheel package
        if: matrix.python-version == '3.10'
        uses: actions/upload-artifact@v4
        with:
          name: keboola_mcp_server-${{ steps.get_version.outputs.version }}-${{ github.sha }}-py3-none-any.whl
          path: dist/keboola_mcp_server-${{ steps.get_version.outputs.version }}-py3-none-any.whl
          retention-days: 7
