name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  SERVICE_IMAGE_NAME: "keboola/mcp-server"
  # SERVICE_ECR_REPOSITORY: "keboola/mcp-server"
  # SERVICE_ECR_PUSH_ROLE: "arn:aws:iam::968984773589:role/kbc-ecr-ApiServicePushRole-fG1HxhQrB2KA"
  # SERVICE_ECR_REGION: "us-east-1"
  # SERVICE_ACR_REPOSITORY: "mcp-server"
  # SERVICE_ACR_REGISTRY: "keboola.azurecr.io"
  # SERVICE_ACR_USERNAME: "mcp-server-push"
  GCP_REGISTRY: "us-central1-docker.pkg.dev"
  GCP_REPOSITORY: "keboola-prod-artifacts/mcp-server"
  GCP_IMAGE_NAME: "mcp-server"
  GCP_IDENTITY_PROVIDER: "projects/388088979044/locations/global/workloadIdentityPools/github/providers/github"
  GCP_SERVICE_ACCOUNT: "mcp-server-ci-push@keboola-prod-artifacts.iam.gserviceaccount.com"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to Docker Hub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx # Assign an id to refer to outputs

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile # Explicitly specify the Dockerfile path
          tags: |
            ${{ env.SERVICE_IMAGE_NAME }}:production-${{ github.sha }}
            ${{ env.SERVICE_IMAGE_NAME }}:canary-orion-${{ github.sha }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}

      - id: 'authGcp'
        name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          create_credentials_file: true
          workload_identity_provider: ${{ env.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Tag and push docker image to Google GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GCP_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.authGcp.outputs.access_token }}

      - name: Push image to GCP GAR
        shell: bash
        run: |
          docker tag $SERVICE_IMAGE_NAME:production-${{ github.sha }} $GCP_REGISTRY/$GCP_REPOSITORY/$GCP_IMAGE_NAME:production-${{ github.sha }}
          docker tag $SERVICE_IMAGE_NAME:canary-orion-${{ github.sha }} $GCP_REGISTRY/$GCP_REPOSITORY/$GCP_IMAGE_NAME:canary-orion-${{ github.sha }}
          docker push $GCP_REGISTRY/$GCP_REPOSITORY/$GCP_IMAGE_NAME:production-${{ github.sha }}
          docker push $GCP_REGISTRY/$GCP_REPOSITORY/$GCP_IMAGE_NAME:canary-orion-${{ github.sha }}

      - name: Trigger image tag update
        if: github.ref == 'refs/heads/main'
        uses: keboola/kbc-stacks/.github/actions/trigger-image-tag-update@main
        with:
          helm-chart: "mcp-server"
          image-tag: canary-orion-${{ github.sha }}
          github-app-private-key: ${{ secrets.GITOPS_KBC_STACKS_TRIGGER_APP_PVK }}
